name: tar-splunk-apps
run-name: ${{ github.actor }} is converting the Splunk apps to .tgz
on: [push]
jobs:
    tar-apps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.3
            - run: tar -zcf ./zipped_apps/*.tgz ./apps/*