name: tar-splunk-apps
on: [push]
jobs:
    tar-apps:
        runs-on: ubuntu-latest
        steps:
            - name: checkout-files
              uses: actions/checkout@v3.5.3
            - name: make-zipped-apps-dir
              run: mkdir -p zipped_apps
            - name: print-show-1
              run: pwd; ls; tree; ls ./apps
            - name: tar-apps
              run: for i in $(find "./apps" -name "*" -maxdepth 1 -mindepth 1 -type d -exec basename {} \;); do tar --format ustar -cvzf ./zipped_apps/$i.tar -C ./apps $i && gzip -v ./zipped_apps/$i.tar; done
            - name: print-show-2
              run: pwd; ls; tree
            - uses: actions/upload-artifact@v3
              with:
                name: zipped-apps
                path: ./zipped_apps
            - name: Commit files  # transfer the new html files back into the repository
              run: |
                git config --local user.name  ${{ github.actor }}        
                git config --local user.email "${{ github.actor }}@users.noreply.github.com"
                git add ./zipped_apps/\*.tar.gz
                git commit -am "Adding the zipped apps to the repo"
                git push -f origin main

              







# name: tar-splunk-apps
# on: [push]
# jobs:
#     tar-apps:
#         runs-on: ubuntu-latest
#         steps:
#             - name: checkout-files
#               uses: actions/checkout@v3.5.3
#             # - name: tar-apps
#             #   run: tar -zcf ./zipped_apps/*.tgz ./apps/*
#             - name: make-zipped-apps
#               run: mkdir zipped_apps
#             - name: Compress action step
#               uses: a7ul/tar-action@v1.1.0
#               id: compress
#               with:
#                 command: c
#                 cwd: .
#                 files: |
#                    ./apps/james_*
#                 outPath: apps.tgz
#             - name: print-show
#               run: pwd; ls; tree
#             - name: Extract files
#               uses: a7ul/tar-action@v1.1.0
#               id: extract
#               with:
#                 command: x
#                 cwd: ./zipped_apps
#                 files: apps.tgz