name: tar-splunk-apps
on: [push]
jobs:
    tar-apps:
        runs-on: ubuntu-latest
        steps:
            - name: checkout-files
              uses: actions/checkout@v3.5.3
            - name: make-zipped-apps-dir
              run: mkdir zipped_apps
            - name: print-show-1
              run: pwd; ls; tree
            - name: tar-apps
              run: for i in $(find ~/apps -name "./*" -level 0 -type d -mtime +14 -exec basename {} \;); do tar -cvf $i.tgz $i; done
            - name: print-show-2
              run: pwd; ls; tree








# name: tar-splunk-apps
# on: [push]
# jobs:
#     tar-apps:
#         runs-on: ubuntu-latest
#         steps:
#             - name: checkout-files
#               uses: actions/checkout@v3.5.3
#             # - name: tar-apps
#             #   run: tar -zcf ./zipped_apps/*.tgz ./apps/*
#             - name: make-zipped-apps
#               run: mkdir zipped_apps
#             - name: Compress action step
#               uses: a7ul/tar-action@v1.1.0
#               id: compress
#               with:
#                 command: c
#                 cwd: .
#                 files: |
#                    ./apps/james_*
#                 outPath: apps.tgz
#             - name: print-show
#               run: pwd; ls; tree
#             - name: Extract files
#               uses: a7ul/tar-action@v1.1.0
#               id: extract
#               with:
#                 command: x
#                 cwd: ./zipped_apps
#                 files: apps.tgz